# Generated by Django 5.0.6 on 2024-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_likepost_comment_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='profile_images/blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
